### ISSUE TITLE
USWDS - Bug: [YOUR TITLE]

### ISSUE THREAD

**Issue by hammad-awan** [uswds/uswds#6031]
### Describe the bug

x

### Steps to reproduce the bug

x

### Expected Behavior

x

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by hammad-awan** [comment]
> Thank you for reporting this, are you able to provide a sample repo or code sandbox where we can reproduce and test this issue?

Unfortunately, I am not allowed to provide any proprietary code for the government that I've written here.

But it isn't much more than taking the contents of the example provided on the USWDS website for the Date Picker Component:

<label class="usa-label" id="appointment-date-label" for="appointment-date"
    >Appointment date</label
  >
  <div class="usa-hint" id="appointment-date-hint">mm/dd/yyyy</div>
  <div #divEl class="usa-date-picker">
    <input
      class="usa-input"
      id="appointment-date"
      name="appointment-date"
      aria-labelledby="appointment-date-label"
      aria-describedby="appointment-date-hint"
    />
  </div>

Wrapping that in an Angular component and then using the Javascript provided methods via the @types index.d.ts files for the uswds__uswds in the appropriate Angular Component class hooks. A developer would import these methods into the component file like this.

import datePicker from '@uswds/uswds/js/usa-date-picker';

Then call:

datePicker.on(divEl.nativeElement) in ngViewOnInit.

where divEl is a ViewChild of type ElementRef to the #divEl template variable placed on the above HTML.

Someone with Angular development experience should know what I'm talking about.

This "turns on" the Javascript related functionality for the component, but when the button is pressed, the date popup does not display. If breakpoints are set in the Javascript code when the date picker is toggled the popup can be seen when it is hit, but as soon as debugging is continued it disappears. This is how it functions without breakpoints as well so it's not just a matter of debugging.

**Comment by hammad-awan** [comment]
Hello,

It appears that this issue is caused if both a package's javascript file is imported into an angular component and the uswds.min.js is included as part of the scripts file in angular.json. If the latter is removed, the issue no longer happens.

Regards.

**Comment by mahoneycm** [comment]
Hey there @hammad-awan ! Thank you for the updates.

We have this scheduled to dive deeper during our next sprint. In the meantime, would you consider setting up a demo repo / code sandbox that showcases this problem since we do not have access to your repo? It would help us to streamline or issue confirmation and troubleshooting by allowing us to jump right into a matching setup.

Some possible options could be:

- [CodePen](https://codepen.io/)
- [StackBlitz](https://stackblitz.com/)
- [USWDS-Sandbox](https://github.com/uswds/uswds-sandbox) - This comes with USWDS and USWDS-Compile installed on an 11ty project. You would need to set up Angular.
- Creating a public demo repo on your GitHub account.

I appreciate your time and looking forward to squashing this bug with you!

**Comment by olsonap** [comment]
This should be resolved by PR #6664.

**Comment by annepetersen** [comment]
To @olsonap's point :point_up:, I think we can close this as resolved by #6664

**Comment by nurulhaya** [comment]
Hello, I am still experiencing the same issue with the latest USWDS release (3.13.0). Removing the USWDS script from angular.json (per [this comment](https://github.com/uswds/uswds/issues/6031#issuecomment-2326896717)) allows the calendar to display. Is that the intended usage pattern?

Stackblitz: https://stackblitz.com/edit/uswds-date-picker

**Comment by olsonap** [comment]
@nurulhaya, PR #6664 was released in 3.14.0.
